### ISSUE TITLE
Correct styling to adapt to mplhep v0.2.10+ style

### ISSUE THREAD

**Issue by matthewfeickert** [matthewfeickert/heputils#41]
In https://github.com/scikit-hep/mplhep/pull/239 the default size for ATLAS style figures was updated and this change was released in `mplhep` `v0.2.10`, which apparently has extreme effects in `heputils`:

| `mplhep` `v0.2.9` | `mplhep` `v0.2.10` |
| -- | -- |
| ![example_stack_v0 2 09](https://user-images.githubusercontent.com/5142394/104235475-a770c300-541a-11eb-9b59-458d7bbe6588.png) |  ![example_stack_v0 2 10](https://user-images.githubusercontent.com/5142394/104235505-b0619480-541a-11eb-97ef-d640c8ea5604.png) |

This seems to be an issue on `mplhep`'s side, so this should get cross-listed there given the following

```python
# example.py
import uproot4 as uproot
from heputils import convert
import mplhep
import matplotlib.pyplot as plt


def main():
    root_file = uproot.open("example.root")
    root_hists = [convert.uproot_to_hist(root_file[key]) for key in root_file.keys()]
    data_hist = root_hists[-1]
    simulation_hists = root_hists[:-1]

    mplhep.set_style("ATLAS")
    fig, ax = plt.subplots()
    mplhep.histplot(simulation_hists[0], histtype="fill", ax=ax)
    fig.savefig(f"mplhep_{mplhep.__version__}_example.png")


if __name__ == "__main__":
    main()
```

```
$ python -m pip install --quiet heputils
$ pip list
Package         Version
--------------- ---------
awkward         1.0.2
awkward0        0.15.2
awkward1        1.0.0
boost-histogram 0.11.1
cachetools      4.2.0
certifi         2020.12.5
chardet         4.0.0
click           7.1.2
cycler          0.10.0
future          0.18.2
heputils        0.0.4
hist            2.0.1
histoprint      1.5.2
idna            2.10
kiwisolver      1.3.1
matplotlib      3.3.3
mplhep          0.2.10
numpy           1.19.5
packaging       20.8
Pillow          8.1.0
pip             20.3.3
pyparsing       2.4.7
python-dateutil 2.8.1
requests        2.25.1
scipy           1.6.0
setuptools      51.1.2
six             1.15.0
uncertainties   3.1.5
uproot          4.0.0
uproot3         3.14.2
uproot3-methods 0.10.0
uproot4         4.0.0
urllib3         1.26.2
wheel           0.36.2
$ curl -sL https://raw.githubusercontent.com/matthewfeickert/heputils/master/tests/example_files.py | python
$ file example.root 
example.root: ROOT file Version 1061800 (Compression: 256)
$ python example.py
$ pip install --upgrade "mplhep<0.2.10"
$ python -m pip list | grep mplhep
mplhep                 0.2.9
$ python example.py
```

produces

| `mplhep` `v0.2.9` | `mplhep` `v0.2.10` |
| -- | -- |
| ![mplhep_0 2 9_example](https://user-images.githubusercontent.com/5142394/104237543-d3da0e80-541d-11eb-88ca-a314ca448163.png) | ![mplhep_0 2 10_example](https://user-images.githubusercontent.com/5142394/104237558-d9375900-541d-11eb-8916-5a5d8cab7d5f.png) |

Given this I'll cross post at `mplhep` but I'll tag @andrzejnovak and @kratsg here too.

**Comment by kratsg** [comment]
This part of the style is tricky. ATLAS [explicitly requires](https://twiki.cern.ch/twiki/bin/viewauth/AtlasProtected/PubComPlotStyle) / allows only two sizes:

> Your result might require a particular size of the drawing canvas, or multiple plots in the same canvas: in this case you should choose the plot size that best fits your needs. But in most cases you will be producing a single plot in a single canvas, either rectangular or square. In this case, use the recommended standard sizes:
>
>* Rectangular plot: 800x600 px
>* Square plot: 600x600 px

so in the linked PR (#239) I changed to 8in by 6in with 100 dpi for print (e.g. to pdf/png). This should give you 800px by 600px images consistently, but when drawing to a screen, this can vary (because matplotlib does not specify image sizes using pixels).
